const productos=[
    {
        id:"1",
        name:"Mause Gaming HP",
        description:"Gamer Mouse, RGB, last generation censors, wireless",
        code: 69,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Fabacomp.cl%2Fproducto%2Fmouse-gamer-hp-g200-negro-2%2F&psig=AOvVaw2-4IRTK4udnL7AaeJl2PfY&ust=1687379370977000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCMCE6pHY0v8CFQAAAAAdAAAAABAJ"],
        category:"",
        price:15.99,
        stock:500,
        heading:"Atrévete-te-te",
    },
    {
        id:"2",
        name:"Mause Gaming Redragon",
        description:"Gamer Mouse, RGB, last generation censors, cabling",
        code: 5565,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Fsimple.ripley.cl%2Fmouse-gamer-redragon-impact-m908-rgb-pro-mpm00017660338&psig=AOvVaw2o98jbwfPFR-vsZt6421d1&ust=1687379409964000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCKiVrqTY0v8CFQAAAAAdAAAAABAG"],
        category:"",
        price:20.75,
        stock:250,
        heading:"salte del closet",
    },
    {
        id:"3",
        name:"Mause Gaming Logitech",
        description:"Gamer Mouse, last generation censors, cabling",
        code: 6696,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.eforest.cl%2Fmouse-gamer-logitech-g-series-g502-hero-negro%2Fp%2FMLC12866864&psig=AOvVaw1QQv91gQR_mOkgMG6p_keu&ust=1687379448889000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCMic_bbY0v8CFQAAAAAdAAAAABAS"],
        category:"",
        price:50.25,
        stock:650,
        heading:"Destápate, quítate el esmalte",
    },
    {
        id:"4",
        name:"Mause Gaming Razer",
        description:"Gamer Mouse, last generation censors, wireless",
        code: 1101,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Fsimple.ripley.cl%2Fmouse-gamer-razer-viper-8khz-ambidextrous-pro-16000-dpi-rgb-mpm00050147788&psig=AOvVaw2Uoghp-xTKVT9MQfzvVZTd&ust=1687379483485000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCKikvcfY0v8CFQAAAAAdAAAAABAF"],
        category:"",
        price:69.96,
        stock:100,
        heading:"Deja de taparte",
    },
    {
        id:"5",
        name:"Mause Gaming Corsair",
        description:"Gamer Mouse, RGB, last generation censors, wireless",
        code: 6549,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.spdigital.cl%2Fmouse-gamer-corsair-dark-core-rgb-se-performance-wired-wireless-with-qi-wireless-charging%2F&psig=AOvVaw1VRvlm3xG34A22Kpyc5CXg&ust=1687379548163000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCOjmsubY0v8CFQAAAAAdAAAAABAc"],
        category:"",
        price:69.96,
        stock:100,
        heading:"Que nadie va a retratarte",
    },
    {
        id:"6",
        name:"Mause Gaming Predator",
        description:"Gamer Mouse, RGB, wireless",
        code: 6415,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ldlc.com%2Fen%2Fproduct%2FPB00467123.html&psig=AOvVaw0o9BjQxPf4769oSzuwvzgm&ust=1687379800616000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCPiQzt7Z0v8CFQAAAAAdAAAAABAJ"],
        category:"",
        price:50,
        stock:169,
        heading:"Levántate, ponte hyper",
    },
    {
        id:"7",
        name:"Mechanical keyboard Predator",
        description:"Gamer Keyboard, mechanical, RGB, mesh cable",
        code: 2323,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ebay.com%2Fitm%2F155030570791&psig=AOvVaw1SS3KKEo2noHwpI4CEw_G2&ust=1687380305935000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJirwc_b0v8CFQAAAAAdAAAAABAE"],
        category:"",
        price:65.58,
        stock:95,
        heading:"Préndete, sácale chispas al starter",
    },
    {
        id:"8",
        name:"Mechanical keyboard HP",
        description:"Gamer Keyboard, mechanical, mesh cable",
        code: 8614,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Fsimple.ripley.cl%2Fteclado-gamer-membrana-hp-k110-led-rgb-qwerty-anti-ghosting-mpm00011567104&psig=AOvVaw3wh7pLBYkB7y1VjkiWxnhL&ust=1687380453699000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCPCWgpbc0v8CFQAAAAAdAAAAABAW"],
        category:"",
        price:12.58,
        stock:999,
        heading:"Sacúdete el sudor como si fueras un wiper",
    },
    {
        id:"9",
        name:"Mechanical keyboard Redragon",
        description:"Gamer Keyboard, mesh cable",
        code: 2152,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.dontwasteyourmoney.com%2Fbest-redragon-gaming-keyboard%2F&psig=AOvVaw1-hLeRw-thOHo5ppo0_An6&ust=1687385734826000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCMCnn-zv0v8CFQAAAAAdAAAAABAE"],
        category:"",
        price:22.58,
        stock:969,
        heading:"Que tú eres callejera, Street Fighter",
    },
    {
        id:"10",
        name:"Mechanical keyboard Logitech",
        description:"Gamer Keyboard, mechanical, RGB",
        code: 2152,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.digitaltrends.com%2Fnews%2Flogitech-g-pro-x-keyboard-review%2F&psig=AOvVaw1KV59GzdoW-eA1hJwvMtOJ&ust=1687386068615000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCIjswYvx0v8CFQAAAAAdAAAAABAJ"],
        category:"",
        price:22.58,
        stock:35,
        heading:"Cambia esa cara de seria",
    },
    {
        id:"11",
        name:"Mechanical keyboard Razer",
        description:"Gamer Keyboard, mechanical, RGB, mesh cable",
        code: 5565,
        photos:["https://m.media-amazon.com/images/S/aplus-media/vc/6d97abd3-310e-48eb-9421-f31633c9dab0._CR0,0,600,450_PT0_SX600__.jpg"],
        category:"",
        price:98.99,
        stock:899,
        heading:"Esa cara de intelectual, de enciclopedia",
    },
    {
        id:"12",
        name:"Mechanical keyboard Corsair",
        description:"Gamer Keyboard, mechanical, RGB",
        code: 4546,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.bestbuy.com%2Fsite%2Fcorsair-k70-pro-mini-wireless-60-rgb-mechanical-cherry-mx-speed-linear-switch-gaming-keyboard-with-swappable-mx-switches-black%2F6510203.p%3FskuId%3D6510203&psig=AOvVaw2LVMF14-cvAvhAZI17kISN&ust=1687477957032000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJCT9rPH1f8CFQAAAAAdAAAAABAK"],
        category:"",
        price:10.22,
        stock:333,
        heading:"Que te voy a inyectar con la bacteria",
    },
    {
        id:"13",
        name:"HP Gamer Headset",
        description:"wireless headphones, stereo sound, microphone",
        code: 6941,
        photos:["https://www.google.com/search?q=headset+gaming+hp&tbm=isch&ved=2ahUKEwipmcKUyNX_AhUzAtQKHRqXDssQ2-cCegQIABAA&oq=headset+gaming+hp&gs_lcp=CgNpbWcQAzIFCAAQgAQyBggAEAgQHjIGCAAQCBAeMgYIABAIEB4yBggAEAgQHjIGCAAQCBAeMgYIABAIEB4yBggAEAgQHjIGCAAQCBAeMgYIABAIEB46BAgjECc6BAgAEB5QnRJY2RdggBpoAHAAeACAAYMGiAGeDpIBDTEuMS4wLjEuMC4xLjGYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=EY6TZOnMNrOE0AaarrrYDA&client=opera-gx&hs=C5l#imgrc=0rR_UAlv0Qh0gM"],
        category:"",
        price:19.20,
        stock:1065,
        heading:"Pa' que de' vuelta' como machina de feria",
    },
    {
        id:"14",
        name:"Redragon Gamer Headset",
        description:"wireless headphones, stereo sound",
        code: 6941,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.kabum.com.br%2Fproduto%2F227818%2Fheadset-gamer-redragon-zeus-x-chroma-mk-ii-rgb-surround-7-1-usb-drivers-53mm-preto-vermelho-h510-rgb&psig=AOvVaw3HFJnVcD19NUsBTxU3Gl1y&ust=1687478731525000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCOjvpaXK1f8CFQAAAAAdAAAAABAX"],
        category:"",
        price:40,
        stock:10,
        heading:"Señorita intelectual, ya sé que tiene el area abdominal",
    },
    {
        id:"15",
        name:"Logitech Gamer Headset",
        description:"wireless headphones, stereo sound, microphone",
        code: 6222,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Ftienda.lancenter.cl%2Fheadsetaudifonos%2F1736-logitech-g-pro-x-gaming-headset-71-league-of-legends-edition.html&psig=AOvVaw0X6ZpakfOoWyZ25sHqHcA6&ust=1687479153913000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCPiow-7L1f8CFQAAAAAdAAAAABAF"],
        category:"",
        price:964,
        stock:1,
        heading:"Que va a explotar como fiesta patronal",
    },
    {
        id:"16",
        name:"Razer Gamer Headset",
        description:"wireless headphones, stereo sound, microphone",
        code: 6951,
        photos:["https://www.google.com/url?sa=i&url=https%3A%2F%2Fpaisdigital.org%2Fcategory%2Fpais-digital%2F%3Fpa%3D2.146.3797250.2.24.56.razer%2Bgaming%2Bearphones&psig=AOvVaw0Xk_6FlPpvcR-NGaWjV2tk&ust=1687479909583000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCKCT5dbO1f8CFQAAAAAdAAAAABAF"],
        category:"",
        price:5,
        stock:152,
        heading:"Que va explotar, como palestino",
    },

]


// interface ProductAttributes {
//     id: string;
//     name: string;
//     description: string | null;
//     code: number;
//     photos: string[];
//     category: string;
//     price: number | 0;
//     stock: number | 0;
//     heading: string | null;
//   }